<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <!-- We are NOT testing a mock. Please... -->
    <SonarQubeSetting Include="sonar.coverage.exclusions">
      <Value>Program.cs</Value>
    </SonarQubeSetting>
  </ItemGroup>
</Project>