using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using Microsoft.CodeAnalysis;

namespace Unity.Services.Cli.Generators;

/// <summary>
/// Source generator that replaces runtime reflection-based discovery of
/// <c>NetworkTargetEndpoints</c> subclasses with a compile-time registry.
///
/// At build time, this generator scans the current compilation and all referenced
/// assemblies that depend on <c>Unity.Services.Cli.Common</c> to find every concrete,
/// non-abstract, non-generic class that inherits from <c>NetworkTargetEndpoints</c>.
/// It emits an <c>EndpointRegistry</c> class with a <c>GetAllEndpoints()</c> method
/// that returns a pre-built array of all discovered endpoint instances.
///
/// Adding a new <c>NetworkTargetEndpoints</c> subclass anywhere in the dependency graph
/// is all that's needed — the generator picks it up automatically on the next build.
/// </summary>
[Generator]
public class EndpointRegistryGenerator : IIncrementalGenerator
{
    const string k_BaseTypeName = "Unity.Services.Cli.Common.Networking.NetworkTargetEndpoints";

    /// <summary>
    /// Registers an incremental pipeline that watches the full compilation,
    /// discovers all endpoint types, and emits <c>EndpointRegistry.g.cs</c>.
    /// </summary>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var source = context.CompilationProvider.Select(static (compilation, ct) =>
        {
            var baseType = compilation.GetTypeByMetadataName(k_BaseTypeName);
            if (baseType is null)
                return "";

            var endpointTypes = new List<INamedTypeSymbol>();

            CollectEndpointTypes(compilation.Assembly.GlobalNamespace, baseType, endpointTypes, ct);

            var localAssemblies = compilation
                .SourceModule
                .ReferencedAssemblySymbols
                .Where(sym => sym.Name.StartsWith("Unity.Services.", StringComparison.OrdinalIgnoreCase));
            foreach (var reference in localAssemblies)
            {
                CollectEndpointTypes(reference.GlobalNamespace, baseType, endpointTypes, ct);
            }

            return GenerateSource(endpointTypes);
        });

        context.RegisterSourceOutput(source, static (spc, sourceText) =>
        {
            if (!string.IsNullOrEmpty(sourceText))
                spc.AddSource("EndpointRegistry.g.cs", sourceText);
        });
    }

    /// <summary>
    /// Builds the source text for the <c>EndpointRegistry</c> class containing
    /// a <c>new T()</c> entry for each discovered endpoint type.
    /// </summary>
    static string GenerateSource(List<INamedTypeSymbol> types)
    {
        var entries = string.Join(
            "\n",
            types.Select(t => $"new {t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}(),"));

        return $@"// <auto-generated/>
#nullable disable

namespace Unity.Services.Cli;

internal static class EndpointRegistry
{{
    internal static global::Unity.Services.Cli.Common.Networking.NetworkTargetEndpoints[] GetAllEndpoints()
    {{
        return new global::Unity.Services.Cli.Common.Networking.NetworkTargetEndpoints[]
        {{
{entries}
        }};
    }}
}}
";
    }

    /// <summary>
    /// Recursively walks a namespace tree and collects all concrete
    /// <c>NetworkTargetEndpoints</c> subclasses into <paramref name="results"/>.
    /// </summary>
    static void CollectEndpointTypes(
        INamespaceSymbol ns,
        INamedTypeSymbol baseType,
        List<INamedTypeSymbol> results,
        CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        foreach (var member in ns.GetMembers())
        {
            if (member is INamespaceSymbol childNs)
            {
                CollectEndpointTypes(childNs, baseType, results, ct);
            }
            else if (member is INamedTypeSymbol type && IsConcreteEndpointType(type, baseType))
            {
                results.Add(type);
            }
        }
    }

    /// <summary>
    /// Returns <c>true</c> if <paramref name="assembly"/> directly references
    /// the assembly identified by <paramref name="target"/>. Used to skip assemblies
    /// (e.g. System.*, third-party) that cannot contain endpoint subclasses.
    /// </summary>
    static bool ReferencesAssembly(IAssemblySymbol assembly, AssemblyIdentity target)
    {
        foreach (var module in assembly.Modules)
        {
            foreach (var referenced in module.ReferencedAssemblySymbols)
            {
                if (referenced.Identity.Equals(target))
                    return true;
            }
        }

        return false;
    }

    /// <summary>
    /// Returns <c>true</c> if <paramref name="type"/> is a non-abstract, non-generic
    /// class that inherits (directly or transitively) from <paramref name="baseType"/>.
    /// </summary>
    static bool IsConcreteEndpointType(INamedTypeSymbol type, INamedTypeSymbol baseType)
    {
        if (type.IsAbstract || type.TypeKind != TypeKind.Class || type.TypeParameters.Length > 0)
            return false;

        var current = type.BaseType;
        while (current != null)
        {
            if (SymbolEqualityComparer.Default.Equals(current, baseType))
                return true;
            current = current.BaseType;
        }

        return false;
    }
}
