<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <!-- We are NOT testing a mock. Please... -->
    <SonarQubeSetting Include="sonar.coverage.exclusions">
      <Value>Program.cs,**/Form1.cs,**/Form1.Designer.cs</Value>
    </SonarQubeSetting>
  </ItemGroup>
</Project>